### ISSUE TITLE
Hi, I encounter a bunch of problems when configuring uBoot.

### ISSUE THREAD

**Issue by targetnull** [ckuethe/usbarmory#4]
@ckuethe <br />
Hi,
When I follow the instructions in [This project](https://github.com/ckuethe/usbarmory/wiki/QEMU-Virtual-Armory) to compile uBoot, I get stuck in the configuration of uBoot.
You say ``
$ vi include/configs/vexpress_common.h

```
# add CONFIG_RSA, CONFIG_FIT_SIGNATURE, CONFIG_CMD_EXT2

# change the environment config to point to MMC

# fix compiled-in config

# maybe disable environment manipulation?

# maybe change TEXT_BASE, or use mkimage to allow loading by "qemu -bios"?``
```

<br />However, I don't see anything relevant in **include/configs/vexpress_common.h**. How should I "_add CONFIG_RSA, CONFIG_FIT_SIGNATURE, CONFIG_CMD_EXT2_" and what is "_environment config_"?<br />I tried to manually *_#define CONFIG_RSA  1 *_, which caused an error when I run "make".

I would appreciate it if you could spare a minute to help me solve the problem.
Thanks a lot.

**Comment by targetnull** [comment]
@ckuethe 
If you are not available at present, please send me an email to yzh07137@126.com when it is convenient to you.
Thanks:)

**Comment by ckuethe** [comment]
This page is mostly notes of experimental approaches, rather than a fully working configuration. I also haven't had any success in getting RSA checking to work - please let me know if you get it to work.

**Comment by targetnull** [comment]
@ckuethe Okay....but how do you know that you should set RSA, from someone's blog? If I just skip those configs, will it still work?

**Comment by ckuethe** [comment]
reading the uboot sources (all the Kconfigs) to see what all the options are. Try configuring for the vexpress, to see if you can get that to work first, before adding any extra options... I had some problems with qemu's emulation of the flash, and could never get uboot to save to the emulated flash device

**Comment by targetnull** [comment]
I'll try that.
If I get it to work, I'll let you know ASAP.
Thanks any way.
